nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['*']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/': null
        '^/api/chapitre': 
            allow_origin: ['http://localhost:3000'] # Autorise les requêtes depuis votre application React
            allow_headers: ['*']
            allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE']
            max_age: 3600
    # defaults:
    #     allow_credentials: false
    #     allow_origin: ['http://localhost:3000'] # Autorise les requêtes depuis votre application React
    #     allow_headers: []
    #     allow_methods: []
    #     expose_headers: []
    #     max_age: 0
    #     hosts: []
    #     origin_regex: false
    #     forced_allow_origin_value: null
    # paths:
    #     '^/': # Chemin de base, vous pouvez ajuster selon vos besoins
    #         allow_origin: ['http://localhost:3000'] # Autorise les requêtes depuis votre application React
    #         allow_headers: ['*']
    #         allow_methods: ['GET', 'POST', 'PUT', 'DELETE']
    #         max_age: 3600
